- name: Create directory
  file:
    path: ~/deploy
    state: directory

- name: Copy files
  become: true
  copy:
    src: /home/sheno-people.tar.gz
    dest: /home/ubuntu/sheno-people.tar.gz

- name: Unarchive sheno-people.tar.gz
  unarchive:
    src: /home/ubuntu/sheno-people.tar.gz
    dest: ~/deploy/
    remote_src: yes

- name: Start PM2
  shell: |
    . ~/.bash_profile
    cd ~/deploy/
    sudo npm cache clean -f
    sudo npm install -g n
    sudo n 12.0
    PATH="$PATH"
    sudo apt install node-typescript
    sudo npm i ts-node typescript
    sudo npm i
    pm2 start main.js
